export const GET_ALBUMS_HORIZONTAL_REQUEST = 'GET_ALBUMS_HORIZONTAL_REQUEST';
export const GET_ALBUMS_HORIZONTAL_SUCCESS = 'GET_ALBUMS_HORIZONTAL_SUCCESS';
export const GET_ALBUMS_HORIZONTAL_FAILED = 'GET_ALBUMS_HORIZONTAL_FAILED';

export const GET_ALBUMS_VERTICAL_REQUEST = 'GET_ALBUMS_VERTICAL_REQUEST';
export const GET_ALBUMS_VERTICAL_SUCCESS = 'GET_ALBUMS_VERTICAL_SUCCESS';
export const GET_ALBUMS_VERTICAL_FAILED = 'GET_ALBUMS_VERTICAL_FAILED';
